# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('einrichtungen', '0013_merge_20161206_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benachrichtigung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('erledigt', models.BooleanField(default=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BettengeldsatzLaeuftAusBenachrichtigung',
            fields=[
                ('benachrichtigung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benachrichtigungen.Benachrichtigung')),
                ('bettengeldsatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auslauf_benachrichtigungen', to='einrichtungen.Bettengeldsatz')),
            ],
            bases=('benachrichtigungen.benachrichtigung',),
        ),
        migrations.CreateModel(
            name='BuchungskennzeichenBenachrichtigung',
            fields=[
                ('benachrichtigung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benachrichtigungen.Benachrichtigung')),
            ],
            bases=('benachrichtigungen.benachrichtigung',),
        ),
        migrations.CreateModel(
            name='EinrichtungHatPflegesatzLaeuftAusBenachrichtigung',
            fields=[
                ('benachrichtigung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benachrichtigungen.Benachrichtigung')),
                ('einrichtung_hat_pflegesatz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auslauf_benachrichtigungen', to='einrichtungen.EinrichtungHatPflegesatz')),
            ],
            bases=('benachrichtigungen.benachrichtigung',),
        ),
        migrations.CreateModel(
            name='FerienBenachrichtigung',
            fields=[
                ('benachrichtigung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benachrichtigungen.Benachrichtigung')),
                ('jahr', models.IntegerField()),
                ('einrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferien_benachrichtigungen', to='einrichtungen.Einrichtung')),
            ],
            bases=('benachrichtigungen.benachrichtigung',),
        ),
        migrations.CreateModel(
            name='SchliesstageBenachrichtigung',
            fields=[
                ('benachrichtigung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benachrichtigungen.Benachrichtigung')),
                ('jahr', models.IntegerField()),
                ('einrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schliesstage_benachrichtigungen', to='einrichtungen.Einrichtung')),
            ],
            bases=('benachrichtigungen.benachrichtigung',),
        ),
        migrations.CreateModel(
            name='SchuelerInEinrichtungLaeuftAusBenachrichtigung',
            fields=[
                ('benachrichtigung_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='benachrichtigungen.Benachrichtigung')),
                ('schueler_in_einrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auslauf_benachrichtigungen', to='einrichtungen.SchuelerInEinrichtung')),
            ],
            bases=('benachrichtigungen.benachrichtigung',),
        ),
    ]
