# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schueler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anwesenheit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(db_index=True, verbose_name='Datum')),
                ('abwesend', models.BooleanField(default=False, verbose_name='Abwesend')),
                ('schueler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anwesenheit', to='schueler.Schueler', verbose_name='Schüler')),
            ],
            options={
                'verbose_name_plural': 'Anwesenheiten',
                'ordering': ['datum', 'schueler'],
                'verbose_name': 'Anwesenheit',
            },
        ),
        migrations.AlterUniqueTogether(
            name='anwesenheit',
            unique_together=set([('schueler', 'datum')]),
        ),
    ]
