# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('einrichtungen', '0001_initial'),
        ('schueler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechnungEinrichtung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_einrichtung', models.CharField(max_length=30, verbose_name='Name der Einrichtung')),
                ('buchungskennzeichen', models.CharField(max_length=20, verbose_name='Buchungskennzeichen')),
                ('datum_faellig', models.DateField(verbose_name='Fälligkeitsdatum')),
                ('betreuungstage', models.PositiveIntegerField(default=0)),
                ('summe', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Gesamtbetrag')),
                ('einrichtung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnungen', to='einrichtungen.Einrichtung', verbose_name='Einrichtung')),
            ],
            options={
                'verbose_name_plural': 'Einrichtungs-Rechnungen',
                'ordering': ('-rechnung_sozialamt__startdatum', '-rechnung_sozialamt__enddatum', 'rechnung_sozialamt', 'einrichtung'),
                'verbose_name': 'Einrichtungs-Rechnung',
            },
        ),
        migrations.CreateModel(
            name='RechnungSozialamt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_sozialamt', models.CharField(max_length=200)),
                ('anschrift_sozialamt', models.TextField()),
                ('startdatum', models.DateField(verbose_name='Startdatum')),
                ('enddatum', models.DateField(help_text='Das Enddatum muss nach dem Startdatum liegen, darf aber nicht nach dem heutigen Datum liegen. Außerdem müssen Startdatum und Enddatum im gleichen Jahr liegen.', verbose_name='Enddatum')),
                ('sozialamt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnungen', to='schueler.Sozialamt', verbose_name='Sozialamt')),
            ],
            options={
                'verbose_name_plural': 'Sozialamtsrechnungen',
                'ordering': ('-startdatum', '-enddatum', 'sozialamt'),
                'verbose_name': 'Sozialamtsrechnung',
            },
        ),
        migrations.CreateModel(
            name='RechnungsPositionEinrichtung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name_schueler', models.CharField(max_length=62, verbose_name='Name des Schülers')),
                ('fehltage_max', models.PositiveIntegerField(verbose_name='Maximale Fehltage')),
                ('anwesend', models.PositiveIntegerField(verbose_name='Anwesend')),
                ('fehltage', models.PositiveIntegerField(verbose_name='Fehltage')),
                ('fehltage_uebertrag', models.PositiveIntegerField(verbose_name='Übertrag Fehltage ab 1.1. des laufenden Jahres oder Eintritt')),
                ('fehltage_gesamt', models.PositiveIntegerField(verbose_name='Fehltage gesamt')),
                ('fehltage_abrechnung', models.PositiveIntegerField(verbose_name='Fehltage zur Abrechnung im Abrechnungszeitraum')),
                ('zahltage', models.PositiveIntegerField(verbose_name='Zahltage im Abrechnungszeitraum')),
                ('summe', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Summe der Aufwendungen')),
                ('rechnung_einrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='abrechnung.RechnungEinrichtung', verbose_name='Einrichtungs-Rechnung')),
                ('schueler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positionen_einrichtung', to='schueler.Schueler', verbose_name='Schüler')),
            ],
            options={
                'verbose_name_plural': 'Einrichtungs-Rechnungspositionen',
                'ordering': ('schueler', 'rechnung_einrichtung', 'rechnung_einrichtung__rechnung_sozialamt__startdatum'),
                'verbose_name': 'Einrichtungs-Rechnungsposition',
            },
        ),
        migrations.CreateModel(
            name='RechnungsPositionSchueler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('abgerechnet', models.BooleanField(default=False, verbose_name='abgerechnet')),
                ('name_schueler', models.CharField(max_length=62, verbose_name='Name des Schülers')),
                ('name_einrichtung', models.CharField(max_length=20, verbose_name='Einrichtung')),
                ('tag_art', models.CharField(choices=[('ferien', 'Ferientag'), ('schule', 'Schultag')], default='schule', max_length=20, verbose_name='Schul- oder Ferientag')),
                ('abwesend', models.BooleanField(default=False, verbose_name='Abwesenheit')),
                ('pflegesatz', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pflegesatz')),
                ('einrichtung', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positionen_schueler', to='einrichtungen.Einrichtung', verbose_name='Einrichtung')),
                ('rechnung_sozialamt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen_schueler', to='abrechnung.RechnungSozialamt', verbose_name='Sozialamtsrechnung')),
                ('schueler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positionen_schueler', to='schueler.Schueler', verbose_name='Schüler')),
            ],
            options={
                'verbose_name_plural': 'Schüler-Rechnungspositionen',
                'ordering': ('rechnung_sozialamt', 'einrichtung', 'schueler', 'datum'),
                'verbose_name': 'Schüler-Rechnungsposition',
            },
        ),
        migrations.AddField(
            model_name='rechnungeinrichtung',
            name='rechnung_sozialamt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen_einrichtungen', to='abrechnung.RechnungSozialamt', verbose_name='Sozialamtsrechnung'),
        ),
        migrations.AlterUniqueTogether(
            name='rechnungspositionschueler',
            unique_together=set([('schueler', 'datum')]),
        ),
        migrations.AlterUniqueTogether(
            name='rechnungspositioneinrichtung',
            unique_together=set([('schueler', 'rechnung_einrichtung')]),
        ),
        migrations.AlterUniqueTogether(
            name='rechnungsozialamt',
            unique_together=set([('sozialamt', 'startdatum', 'enddatum')]),
        ),
        migrations.AlterUniqueTogether(
            name='rechnungeinrichtung',
            unique_together=set([('rechnung_sozialamt', 'einrichtung')]),
        ),
    ]
