# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnungsozialamt',
            name='enddatum',
            field=models.DateField(help_text=('Das Enddatum muss nach dem Startdatum liegen, ', 'darf aber nicht nach dem heutigen Datum liegen.', ' Außerdem müssen Startdatum und Enddatum im gleichen Jahr liegen.'), verbose_name='Enddatum'),
        ),
    ]
