# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0002_auto_20161025_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='bargeldbetrag',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Bargeldbetrag'),
        ),
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='bekleidungsgeld',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Bekleidungsgeld'),
        ),
    ]
