# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0002_auto_20160810_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnungsozialamt',
            name='enddatum',
            field=models.DateField(help_text='Das Enddatum muss nach dem Startdatum liegen, darf aber nicht nach dem heutigen Datum liegen. Außerdem müssen Startdatum und Enddatum im gleichen Jahr liegen.', verbose_name='Enddatum'),
        ),
    ]
