# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0003_auto_20160811_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnungsposition',
            name='einrichtung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einrichtungen.Einrichtung', verbose_name='Einrichtung'),
        ),
    ]
