# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0004_schuelerineinrichtung_anteile_bargeld'),
        ('abrechnung', '0003_auto_20161102_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bargeldsatz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('lebensjahr', models.IntegerField(choices=[(3, '3. Lebensjahr'), (4, '4. Lebensjahr'), (5, '5. Lebensjahr'), (6, '6. Lebensjahr'), (7, '7. Lebensjahr'), (8, '8. Lebensjahr'), (9, '9. Lebensjahr'), (10, '10. Lebensjahr'), (11, '11. Lebensjahr'), (12, '12. Lebensjahr'), (13, '13. Lebensjahr'), (14, '14. Lebensjahr'), (15, '15. Lebensjahr'), (16, '16. Lebensjahr'), (17, '17. Lebensjahr'), (18, '18. Lebensjahr')], unique=True, verbose_name='Lebensjahr')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Betrag')),
            ],
            options={
                'verbose_name': 'Bargeldsatz',
                'verbose_name_plural': 'Bargeldsätze',
            },
        ),
        migrations.CreateModel(
            name='Bettengeldsatz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('startdatum', models.DateField(verbose_name='Startdatum')),
                ('enddatum', models.DateField(help_text='Das Enddatum muss nach dem Startdatum liegen.', verbose_name='Enddatum')),
                ('satz', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Satz')),
                ('satz_vermindert', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Verminderter Satz')),
                ('einrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bettengeldsaetze', to='einrichtungen.Einrichtung', verbose_name='Einrichtung')),
            ],
            options={
                'verbose_name': 'Bettengeldsatz',
                'verbose_name_plural': 'Bettengeldsätze',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bettengeldsatz',
            unique_together=set([('einrichtung', 'startdatum', 'enddatum')]),
        ),
    ]
