# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0004_auto_20160811_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechnung',
            name='fehltage_nicht_abgerechnet',
        ),
        migrations.AddField(
            model_name='rechnungsposition',
            name='rechnung_nicht_abgerechnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fehltage_nicht_abgerechnet', to='abrechnung.Rechnung', verbose_name='Rechnung, nicht abgerechnet'),
        ),
    ]
