# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0004_auto_20161102_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bargeldsatz',
        ),
        migrations.AlterUniqueTogether(
            name='bettengeldsatz',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='bettengeldsatz',
            name='einrichtung',
        ),
        migrations.DeleteModel(
            name='Bettengeldsatz',
        ),
    ]
