# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0005_auto_20161104_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnungspositionschueler',
            name='vermindert',
            field=models.BooleanField(default=False, verbose_name='Verminderter Bettengeldsatz'),
        ),
    ]
