# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0005_auto_20160824_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechnung',
            name='fehltage_gesamt',
        ),
        migrations.RemoveField(
            model_name='rechnung',
            name='max_fehltage',
        ),
    ]
