# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0014_auto_20160824_1218'),
        ('schueler', '0006_auto_20160823_1451'),
        ('abrechnung', '0006_auto_20160908_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechnungsPositionSchueler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('name_einrichtung', models.CharField(max_length=20, verbose_name='Einrichtung')),
                ('tag_art', models.CharField(choices=[('ferien', 'Ferientag'), ('schule', 'Schultag')], default='schule', max_length=20, verbose_name='Schul- oder Ferientag')),
                ('abwesend', models.BooleanField(default=False, verbose_name='Abwesenheit')),
                ('pflegesatz', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pflegesatz')),
                ('einrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='einrichtungen.Einrichtung', verbose_name='Einrichtung')),
            ],
            options={
                'verbose_name': 'Schüler-Rechnungsposition',
                'verbose_name_plural': 'Schüler-Rechnungspositionen',
                'ordering': ('sozialamt', 'schueler', 'einrichtung', 'datum'),
            },
        ),
        migrations.RenameModel(
            old_name='Rechnung',
            new_name='RechnungSchueler',
        ),
        migrations.AlterUniqueTogether(
            name='rechnungsposition',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='rechnungsposition',
            name='einrichtung',
        ),
        migrations.RemoveField(
            model_name='rechnungsposition',
            name='rechnung',
        ),
        migrations.RemoveField(
            model_name='rechnungsposition',
            name='rechnung_nicht_abgerechnet',
        ),
        migrations.RemoveField(
            model_name='rechnungsposition',
            name='schueler',
        ),
        migrations.RemoveField(
            model_name='rechnungsposition',
            name='sozialamt',
        ),
        migrations.AlterModelOptions(
            name='rechnungschueler',
            options={'ordering': ('-rechnung_sozialamt__startdatum', '-rechnung_sozialamt__enddatum', 'rechnung_sozialamt', 'schueler'), 'verbose_name': 'Schüler-Rechnung', 'verbose_name_plural': 'Schüler-Rechnungen'},
        ),
        migrations.DeleteModel(
            name='RechnungsPosition',
        ),
        migrations.AddField(
            model_name='rechnungspositionschueler',
            name='rechnung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='abrechnung.RechnungSchueler', verbose_name='Schüler-Rechnung'),
        ),
        migrations.AddField(
            model_name='rechnungspositionschueler',
            name='rechnung_nicht_abgerechnet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fehltage_nicht_abgerechnet', to='abrechnung.RechnungSchueler', verbose_name='Schüler-Rechnung, nicht abgerechnet'),
        ),
        migrations.AddField(
            model_name='rechnungspositionschueler',
            name='schueler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schueler.Schueler', verbose_name='Schüler'),
        ),
        migrations.AddField(
            model_name='rechnungspositionschueler',
            name='sozialamt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schueler.Sozialamt', verbose_name='Sozialamt'),
        ),
        migrations.AlterUniqueTogether(
            name='rechnungspositionschueler',
            unique_together=set([('schueler', 'datum')]),
        ),
    ]
