# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0006_rechnungspositionschueler_vermindert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnungspositionschueler',
            name='vermindert',
            field=models.BooleanField(default=False, verbose_name='Verminderter Pflegesatz (Bettengeldsatz)'),
        ),
    ]
