# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0007_auto_20170117_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnungspositionschueler',
            name='name_einrichtung',
            field=models.CharField(max_length=30, verbose_name='Einrichtung'),
        ),
    ]
