# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0007_auto_20160908_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rechnungspositionschueler',
            old_name='rechnung',
            new_name='rechnung_schueler',
        ),
        migrations.AlterField(
            model_name='rechnungschueler',
            name='rechnung_sozialamt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen_schueler', to='abrechnung.RechnungSozialamt', verbose_name='Sozialamtsrechnung'),
        ),
        migrations.AlterField(
            model_name='rechnungschueler',
            name='schueler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen_schueler', to='schueler.Schueler', verbose_name='Schüler'),
        ),
    ]
