# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0007_sozialamt_konto_bic'),
        ('einrichtungen', '0016_auto_20160916_1632'),
        ('abrechnung', '0008_auto_20160908_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='RechnungEinrichtung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('einrichtung_name', models.CharField(max_length=30, verbose_name='Name der Einrichtung')),
                ('buchungskennzeichen', models.CharField(max_length=20, verbose_name='Buchungskennzeichen')),
                ('datum_faellig', models.DateField(verbose_name='Fälligkeitsdatum')),
                ('betreuungstage', models.PositiveIntegerField(default=0)),
                ('summe', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Gesamtbetrag')),
                ('einrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen', to='einrichtungen.Einrichtung', verbose_name='Einrichtung')),
                ('rechnung_sozialamt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechnungen_einrichtungen', to='abrechnung.RechnungSozialamt', verbose_name='Sozialamtsrechnung')),
            ],
            options={
                'verbose_name_plural': 'Einrichtungs-Rechnungen',
                'ordering': ('-rechnung_sozialamt__startdatum', '-rechnung_sozialamt__enddatum', 'rechnung_sozialamt', 'einrichtung'),
                'verbose_name': 'Einrichtungs-Rechnung',
            },
        ),
        migrations.CreateModel(
            name='RechnungsPositionEinrichtung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pers_pflegesatz', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Persönlicher Pflegesatz')),
                ('pers_pflegesatz_ferien', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Persönlicher Pflegesatz Ferien')),
                ('rechnung_einrichtung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='abrechnung.RechnungEinrichtung', verbose_name='Einrichtungs-Rechnung')),
                ('schueler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schueler.Schueler', verbose_name='Schüler')),
            ],
            options={
                'verbose_name_plural': 'Einrichtungs-Rechnungspositionen',
                'ordering': ('schueler', 'rechnung_einrichtung', 'rechnung_einrichtung__rechnung_sozialamt__startdatum'),
                'verbose_name': 'Einrichtungs-Rechnungsposition',
            },
        ),
        migrations.AlterUniqueTogether(
            name='rechnungspositioneinrichtung',
            unique_together=set([('schueler', 'rechnung_einrichtung')]),
        ),
        migrations.AlterUniqueTogether(
            name='rechnungeinrichtung',
            unique_together=set([('rechnung_sozialamt', 'einrichtung')]),
        ),
    ]
