# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0009_auto_20160916_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rechnungspositioneinrichtung',
            name='pers_pflegesatz',
        ),
        migrations.RemoveField(
            model_name='rechnungspositioneinrichtung',
            name='pers_pflegesatz_ferien',
        ),
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='anwesend',
            field=models.PositiveIntegerField(default=0, verbose_name='Anwesend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='fehltage',
            field=models.PositiveIntegerField(default=0, verbose_name='Fehltage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='fehltage_abrechnung',
            field=models.PositiveIntegerField(default=0, verbose_name='Fehltage zur Abrechnung im Abrechnungszeitraum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='fehltage_gesamt',
            field=models.PositiveIntegerField(default=0, verbose_name='Fehltage gesamt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='fehltage_max',
            field=models.PositiveIntegerField(default=0, verbose_name='Maximale Fehltage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='fehltage_uebertrag',
            field=models.PositiveIntegerField(default=0, verbose_name='Übertrag Fehltage ab 1.1. des laufenden Jahres oder Eintritt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='summe',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Summe der Aufwendungen'),
        ),
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='zahltage',
            field=models.PositiveIntegerField(default=0, verbose_name='Zahltage im Abrechnungszeitraum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rechnungeinrichtung',
            name='summe',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Gesamtbetrag'),
        ),
        migrations.AlterField(
            model_name='rechnungschueler',
            name='summe',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Gesamtbetrag'),
        ),
        migrations.AlterField(
            model_name='rechnungspositionschueler',
            name='pflegesatz',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pflegesatz'),
        ),
    ]
