# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0010_auto_20160916_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnungspositioneinrichtung',
            name='name_schueler',
            field=models.CharField(default='', max_length=61, verbose_name='Name des Schülers'),
            preserve_default=False,
        ),
    ]
