# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0011_rechnungspositioneinrichtung_name_schueler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rechnungeinrichtung',
            old_name='einrichtung_name',
            new_name='name_einrichtung',
        ),
    ]
