# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0012_auto_20160916_1916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rechnungschueler',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='rechnungschueler',
            name='rechnung_sozialamt',
        ),
        migrations.RemoveField(
            model_name='rechnungschueler',
            name='schueler',
        ),
        migrations.AlterModelOptions(
            name='rechnungspositionschueler',
            options={'ordering': ('rechnung_sozialamt', 'einrichtung', 'schueler', 'datum'), 'verbose_name': 'Schüler-Rechnungsposition', 'verbose_name_plural': 'Schüler-Rechnungspositionen'},
        ),
        migrations.RemoveField(
            model_name='rechnungspositionschueler',
            name='rechnung_nicht_abgerechnet',
        ),
        migrations.RemoveField(
            model_name='rechnungspositionschueler',
            name='rechnung_schueler',
        ),
        migrations.RemoveField(
            model_name='rechnungspositionschueler',
            name='sozialamt',
        ),
        migrations.AddField(
            model_name='rechnungspositionschueler',
            name='abgerechnet',
            field=models.BooleanField(default=False, verbose_name='abgerechnet'),
        ),
        migrations.AddField(
            model_name='rechnungspositionschueler',
            name='name_schueler',
            field=models.CharField(default='', max_length=61, verbose_name='Name des Schülers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rechnungspositionschueler',
            name='rechnung_sozialamt',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='positionen_schueler', to='abrechnung.RechnungSozialamt', verbose_name='Sozialamtsrechnung'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RechnungSchueler',
        ),
    ]
