# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0013_auto_20160920_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechnungspositioneinrichtung',
            name='schueler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen_einrichtung', to='schueler.Schueler', verbose_name='Schüler'),
        ),
        migrations.AlterField(
            model_name='rechnungspositionschueler',
            name='schueler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen_schueler', to='schueler.Schueler', verbose_name='Schüler'),
        ),
    ]
