# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abrechnung', '0016_auto_20160921_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rechnungsozialamt',
            old_name='sozialamt_anschrift',
            new_name='anschrift_sozialamt',
        ),
        migrations.AddField(
            model_name='rechnungsozialamt',
            name='name_sozialamt',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rechnungeinrichtung',
            name='einrichtung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnungen', to='einrichtungen.Einrichtung', verbose_name='Einrichtung'),
        ),
        migrations.AlterField(
            model_name='rechnungsozialamt',
            name='sozialamt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnungen', to='schueler.Sozialamt', verbose_name='Sozialamt'),
        ),
        migrations.AlterField(
            model_name='rechnungspositioneinrichtung',
            name='schueler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positionen_einrichtung', to='schueler.Schueler', verbose_name='Schüler'),
        ),
        migrations.AlterField(
            model_name='rechnungspositionschueler',
            name='einrichtung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positionen_schueler', to='einrichtungen.Einrichtung', verbose_name='Einrichtung'),
        ),
        migrations.AlterField(
            model_name='rechnungspositionschueler',
            name='schueler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positionen_schueler', to='schueler.Schueler', verbose_name='Schüler'),
        ),
    ]
