# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungskennzeichen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buchungskennzeichen',
            name='buchungskennzeichen',
            field=models.CharField(help_text='Bitte das Buchungskennzeichen ohne Trennpunkte eingeben.', max_length=20, unique=True, verbose_name='Buchungskennzeichen'),
        ),
    ]
