# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('bemerkungen', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
            },
        ),
        migrations.CreateModel(
            name='Schueler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('vorname', models.CharField(max_length=30, verbose_name='Vorname')),
                ('nachname', models.CharField(max_length=30, verbose_name='Nachname')),
                ('geburtsdatum', models.DateField()),
                ('bemerkungen', models.TextField(blank=True)),
                ('aktenzeichen', models.CharField(max_length=30, verbose_name='Aktenzeichen')),
                ('gruppe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schueler', to='schueler.Gruppe')),
            ],
            options={
                'verbose_name': 'Schüler',
                'ordering': ['nachname', 'vorname'],
                'verbose_name_plural': 'Schüler',
            },
        ),
        migrations.CreateModel(
            name='Sozialamt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=35)),
                ('anschrift', models.TextField()),
                ('zahlungspartnernummer', models.CharField(max_length=7, unique=True, verbose_name='Zahlungspartnernummer')),
            ],
            options={
                'verbose_name': 'Sozialamt',
                'verbose_name_plural': 'Sozialämter',
            },
        ),
        migrations.AddField(
            model_name='schueler',
            name='sozialamt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schueler', to='schueler.Sozialamt'),
        ),
    ]
