# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozialamt',
            name='zahlungspartnernummer',
            field=models.CharField(max_length=7, verbose_name='Zahlungspartnernummer'),
        ),
    ]
