# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 07:57
from __future__ import unicode_literals

import absys.apps.schueler.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0002_auto_20161109_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schueler',
            name='geburtsdatum',
            field=models.DateField(validators=[absys.apps.schueler.validators.validate_geburtsdatum_in_vergangenheit], verbose_name='Geburtsdatum'),
        ),
    ]
