# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0003_auto_20160719_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='schueler',
            name='aktenzeichen',
            field=models.CharField(default='test', max_length=30, verbose_name='Aktenzeichen'),
            preserve_default=False,
        ),
    ]
