# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0004_schueler_aktenzeichen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schueler',
            name='buchungsnummer',
        ),
        migrations.AddField(
            model_name='schueler',
            name='pkz',
            field=models.CharField(blank=True, max_length=13, verbose_name='PKZ'),
        ),
    ]
