# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0006_auto_20161202_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schueler',
            name='aktenzeichen',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='PKZ'),
        ),
    ]
