# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0006_auto_20160823_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozialamt',
            name='konto_bic',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
