# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0007_sozialamt_konto_bic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sozialamt',
            name='konto_bic',
        ),
        migrations.RemoveField(
            model_name='sozialamt',
            name='konto_iban',
        ),
        migrations.RemoveField(
            model_name='sozialamt',
            name='konto_institut',
        ),
    ]
