# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0008_auto_20160920_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schueler',
            name='pkz',
        ),
    ]
