# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0009_auto_20161204_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozialamt',
            name='sbkz',
            field=models.CharField(default='', max_length=12, verbose_name='Sozialamtsbuchungskennzeichen'),
            preserve_default=False,
        ),
    ]
