# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0009_remove_schueler_pkz'),
    ]

    operations = [
        migrations.AddField(
            model_name='sozialamt',
            name='zahlungspartnernummer',
            field=models.CharField(default=1234567, max_length=7, unique=True, verbose_name='Zahlungspartnernummer'),
            preserve_default=False,
        ),
    ]
