# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0010_sozialamt_zahlungspartnernummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sozialamt',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
