# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0012_auto_20170119_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='schueler',
            name='inaktiv',
            field=models.BooleanField(default=False, help_text="Schüler können nicht gelöscht, sondern lediglich 'deaktiviert' werden. Dies hat keinerlei Auswirkungen auf die Abrechnung sondern beinflusst lediglich die Darstellung im Frontend, z.B. Gruppenliste."),
        ),
    ]
