# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='einrichtung',
            name='konfiguration',
            field=models.IntegerField(choices=[(250, '250 Tage'), (280, '280 Tage'), (365, '365 Tage')], default=250),
            preserve_default=False,
        ),
    ]
