# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0002_einrichtung_konfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='einrichtung',
            name='konfiguration',
        ),
        migrations.AddField(
            model_name='einrichtung',
            name='konfiguration_id',
            field=models.IntegerField(choices=[(250, '250 Tage'), (280, '280 Tage'), (365, '365 Tage')], default=250, verbose_name='Konfiguration'),
            preserve_default=False,
        ),
    ]
