# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0003_auto_20161102_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='schuelerineinrichtung',
            name='anteile_bargeld',
            field=models.IntegerField(choices=[(0, '0 (keine Auszahlung)'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12 (voller Satz)')], default=12, verbose_name='Anteile Bargeld'),
        ),
    ]
