# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0005_auto_20161104_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bargeldsatz',
            name='betrag',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Betrag pro Monat'),
        ),
    ]
