# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0006_auto_20161108_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettengeldsatz',
            name='satz',
            field=models.DecimalField(decimal_places=2, help_text='<p>Dieses ist Feld ist doppelt belegt:<br><ol><li>Für 280-Tages-Einrichtungen ist dieses Feld der Abwesenheitsvergütungssatz.</li><li>Für 365-Tages-Einrichtungen ist dieses Feld der Bettengeldsatz.</li><ol></p>', max_digits=8, verbose_name='Satz'),
        ),
        migrations.AlterField(
            model_name='einrichtunghatpflegesatz',
            name='pflegesatz',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pflegesatz'),
        ),
        migrations.AlterField(
            model_name='einrichtunghatpflegesatz',
            name='pflegesatz_enddatum',
            field=models.DateField(verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='einrichtunghatpflegesatz',
            name='pflegesatz_ferien',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pflegesatz Ferien'),
        ),
        migrations.AlterField(
            model_name='einrichtunghatpflegesatz',
            name='pflegesatz_startdatum',
            field=models.DateField(verbose_name='Startdatum'),
        ),
    ]
