# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0007_auto_20161201_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettengeldsatz',
            name='satz_vermindert',
        ),
    ]
