# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0007_auto_20161201_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einrichtung',
            name='titel',
            field=models.IntegerField(help_text='Darf maximal fünf Ziffern haben.', verbose_name='Titel'),
        ),
    ]
