# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0008_auto_20161202_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schuelerineinrichtung',
            name='sozialamt',
            field=models.ForeignKey(help_text='<span style="font-size: 1.3em">Es wird automatisch das aktuelle Sozialamt des Schülers ausgewählt.<br><br>Soll der Schüler in dieser Einrichtung ein neues Sozialamt zugewiesen bekommen, muss wie folgt vorgegangen werden:<br><br>1. Das Austrittsdatum des aktuellen Datensatzes auf den letzten Tag für das alte Sozialamt setzen.<br>2. Das Sozialamt am Datensatz des Schülers ändern.<br>3. Einen neuen Schüler-in-Einrichtung-Datensatz für den neuen Zeitraum für den gleichen Schüler der gleichen Einrichtung hinzufügen.<br><br></span>', on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='schueler.Sozialamt'),
        ),
    ]
