# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0009_auto_20160719_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schuelerineinrichtung',
            options={'ordering': ('schueler__nachname', 'schueler__vorname', '-austritt'), 'verbose_name': 'Schüler in Einrichtung', 'verbose_name_plural': 'Schüler in Einrichtungen'},
        ),
    ]
