# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schueler', '0006_auto_20160823_1451'),
        ('einrichtungen', '0010_auto_20160823_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='schuelerineinrichtung',
            name='sozialamt',
            field=models.ForeignKey(null=True, default=None, help_text="<span style=\"font-size: 1.3em\">Es wird automatisch das aktuelle Sozialamt des Schülers ausgewählt.<br><br>Soll der Schüler in dieser Einrichtung ein neues Sozialamt zugewiesen bekommen, muss wie folgt vorgegangen werden:<br><br>1. Das Austrittsdatum des aktuellen Datensatzes auf den letzten Tag für das alte Sozialamt setzen.<br>2. Das Sozialamt am Datensatz des Schülers ändern.<br>3. Den Schüler für den neuen Zeitraum der gleichen Einrichtung hinzufügen.<br><br></span>", on_delete=django.db.models.deletion.CASCADE, related_name='anmeldungen', to='schueler.Sozialamt'),
            preserve_default=False,
        ),
    ]
