# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0011_auto_20161202_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einrichtung',
            name='kuerzel',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kürzel'),
        ),
    ]
