# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 14:25
from __future__ import unicode_literals

from django.db import migrations


def add_sozialamt(apps, schema_editor):
    SchuelerInEinrichtung = apps.get_model('einrichtungen', 'SchuelerInEinrichtung')
    for schueler_in_einrichtung in SchuelerInEinrichtung.objects.all():
        schueler_in_einrichtung.sozialamt = schueler_in_einrichtung.schueler.sozialamt
        schueler_in_einrichtung.save()


def remove_sozialamt(apps, schema_editor):
    SchuelerInEinrichtung = apps.get_model('einrichtungen', 'SchuelerInEinrichtung')
    for schueler_in_einrichtung in SchuelerInEinrichtung.objects.all():
        schueler_in_einrichtung.sozialamt = None
        schueler_in_einrichtung.save()


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0011_schuelerineinrichtung_sozialamt'),
    ]

    operations = [
        migrations.RunPython(add_sozialamt, remove_sozialamt),
    ]
