# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0008_remove_bettengeldsatz_satz_vermindert'),
        ('einrichtungen', '0012_auto_20161204_1419'),
    ]

    operations = [
    ]
