# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0013_auto_20160823_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schliesstag',
            options={'verbose_name': 'Schließ\xadtag', 'verbose_name_plural': 'Schließ\xadtage'},
        ),
        migrations.AddField(
            model_name='schliesstag',
            name='einrichtungen',
            field=models.ManyToManyField(related_name='schliesstage', to='einrichtungen.Einrichtung', verbose_name='Einrichtungen'),
        ),
        migrations.AlterField(
            model_name='schliesstag',
            name='datum',
            field=models.DateField(unique=True),
        ),
    ]
