# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0014_auto_20160824_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('anschrift', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='einrichtung',
            name='standort',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='standorte', to='einrichtungen.Standort'),
            preserve_default=False,
        ),
    ]
