# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0015_auto_20170122_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schulanschrift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('anschrift', models.TextField(default='Musterschule\nMusterstr. 42\n23232 Musterstadt', help_text="Dies ist die Adresse welche auf der Rechnung als Absender eingetragen wird. Brechen Sie die Zeilen mit 'Enter' um.")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
