# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0015_auto_20160909_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standort',
            options={'verbose_name': 'Standort', 'verbose_name_plural': 'Standorte'},
        ),
        migrations.AlterField(
            model_name='einrichtung',
            name='kuerzel',
            field=models.CharField(max_length=3, unique=True, verbose_name='Kürzel'),
        ),
        migrations.AlterField(
            model_name='einrichtung',
            name='standort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einrichtungen', to='einrichtungen.Standort'),
        ),
    ]
