# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0016_schulanschrift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schulanschrift',
            options={'verbose_name': 'Schulanschrift', 'verbose_name_plural': 'Schulanschriften'},
        ),
    ]
