# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0016_auto_20160916_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einrichtunghatpflegesatz',
            name='pflegesatz',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='einrichtunghatpflegesatz',
            name='pflegesatz_ferien',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='schuelerineinrichtung',
            name='pers_pflegesatz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='schuelerineinrichtung',
            name='pers_pflegesatz_ferien',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
