# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0017_auto_20170122_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schulanschrift',
        ),
    ]
