# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0017_auto_20160916_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='standort',
            name='konto_bic',
            field=models.CharField(default='', max_length=12, verbose_name='BIC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standort',
            name='konto_iban',
            field=models.CharField(default='', max_length=22, verbose_name='IBAN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standort',
            name='konto_institut',
            field=models.CharField(default='', max_length=100, verbose_name='Institut'),
            preserve_default=False,
        ),
    ]
