# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0018_auto_20160920_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='einrichtung',
            name='titel',
            field=models.CharField(default=12345, max_length=5, verbose_name='Titel'),
            preserve_default=False,
        ),
    ]
