# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einrichtungen', '0019_einrichtung_titel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='einrichtung',
            name='titel',
            field=models.IntegerField(help_text='Darf maximal fünf Ziffern haben.', unique=True, verbose_name='Titel'),
        ),
    ]
